- name: Install MariaDB
  hosts: database servers
  become: true
  
  tasks:
  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: present
  
  - name: Start MariaDB
    service:
      name: mariadb
      state: started
      enabled: yes